window.GAME_DATA = { people: [
{id:1,name:"Андреев Сергей",f:{assembly:true,management:true,deputy2:true,avg_height:true,balding:true,cap:true,married:true,has_kids:true,has_daughter:true,spouse_here:true,andreev_couple:true}},
{id:2,name:"Андреева Татьяна",f:{assembly:true,ozon:true,thin:true,blonde:true,married:true,has_kids:true,has_daughter:true,spouse_here:true,spouse_mgmt:true,andreev_couple:true}},
{id:3,name:"Аришев Борис",f:{assembly:true,forklift_can:true,best_picker:true,full:true,short_cut:true,unmarried:true,has_kids:true,has_daughter:true}},
{id:4,name:"Бабаджанов Афсар",f:{assembly:true,fast_picker:true,married:true,has_kids:true,has_son:true,has_daughter:true,son_and_daughter:true,loud:true}},
{id:5,name:"Воронцов Сергей",f:{assembly:true,best_picker:true,returned:true,tall:true,graying:true,limp:true,married:true,has_kids:true,has_daughter:true,two_daughters:true,has_car:true,volvo:true,nick_volk:true,fight:true}},
{id:6,name:"Галактионов Владимир",f:{placement:true,placement_only:true,married:true,has_kids:true,grandson:true,fussy:true,moonshine:true}},
{id:7,name:"Горковенко Олег",f:{assembly:true,has_car:true,matiz:true}},
{id:8,name:"Дейнеко Паша",f:{assembly:true,avg_height:true,athletic:true,blonde:true,unmarried:true,has_kids:false,has_car:true,nissan:true,detailing:true}},
{id:9,name:"Дудник Сергей",f:{assembly:true,dyed_hair:true,moldova:true}},
{id:10,name:"Жнивьин Алексей",f:{assembly:true,gray_hair:true,married:true,has_kids:true,has_son:true,cousin_here:true,zhnivin_kin:true,moonshine:true,scooter:true,nick_psih:true,fight:true}},
{id:12,name:"Карабанова Оля",f:{assembly:true,dark_hair:true,married:true}},
{id:13,name:"Козырь Алексей",f:{assembly:true,athletic:true,tattoos:true,bets:true,spartak:true}},
{id:14,name:"Колесников Александр",f:{shipping:true,full:true,glasses:true,loud:true}},
{id:15,name:"Краснощекова Ирина",f:{assembly:true,ozon:true,marketplace_lead:true,short_cut:true,married:true}},
{id:16,name:"Кривошеин Паша",f:{assembly:true,leroy:true,leroy_boss:true,avg_height:true,athletic:true,married:true,has_kids:true,has_daughter:true,has_car:true,ford:true}},
{id:17,name:"Ляшенко Саша",f:{placement:true,returned:true,sheremetyevo:true,below_avg:true,dark_hair:true,divorced:true,has_kids:true,has_son:true}},
{id:18,name:"Мартынюк Василий",f:{receiving:true,short:true,balding:true,unmarried:true,has_kids:false,moldova:true}},
{id:19,name:"Матвеева Елена",f:{assembly:true,short:true,blonde:true,married:true,has_kids:true,has_son:true,three_sons:true}},
{id:20,name:"Носова Мария",f:{assembly:true,short:true,full:true,unmarried:true,has_kids:false}},
{id:21,name:"Подаплелов Иван",f:{assembly:true,receiving:true,young:true,dark_hair:true,unmarried:true,has_kids:false,father_son_here:true,podaplelov_kin:true,bets:true}},
{id:22,name:"Подаплелов Павел",f:{assembly:true,fast_picker:true,married:true,has_kids:true,has_son:true,father_son_here:true,podaplelov_kin:true,has_car:true,lada:true}},
{id:23,name:"Репной Юрий",f:{receiving:true,older:true,graying:true,married:true,has_kids:true,has_son:true,sheremetyevo:true,games:true}},
{id:24,name:"Савочкин Сергей",f:{assembly:true,avg_height:true,dark_hair:true,married:true,has_kids:true,has_son:true,cousin_here:true,zhnivin_kin:true,bets:true,spartak:true}},
{id:25,name:"Сайибов Ойбек",f:{assembly:true,athletic:true,married:true,has_kids:true,spouse_here:true,sayibov_couple:true,has_car:true,priora:true,hoarse:true}},
{id:26,name:"Сайибова Шабнам",f:{assembly:true,dark_hair:true,married:true,has_kids:true,spouse_here:true,sayibov_couple:true}},
{id:27,name:"Седов Александр",f:{assembly:true,short:true,blonde:true,married:true,recently_married:true,rap:true}},
{id:28,name:"Семерикова Алёна",f:{assembly:true,ozon:true,short:true,dark_hair:true,short_cut:true,has_kids:false}},
{id:29,name:"Серов Руслан",f:{placement:true,returned:true,red_hair:true,has_kids:false,has_car:true,mitsubishi:true}},
{id:30,name:"Смирнов Андрей",f:{assembly:true,leroy:true,above_avg:true,athletic:true,short_cut:true,married:true,has_kids:true,has_son:true,has_car:true,skoda:true}},
{id:31,name:"Степин Виктор",f:{defect:true,full:true,gray_hair:true,older:true,married:true,has_kids:true,has_son:true}},
{id:32,name:"Тищенко Стас",f:{management:true,deputy:true,avg_height:true,bald:true,married:true,has_kids:true,has_son:true,spouse_here:true,both_mgmt_couple:true,tishchenko_couple:true}},
{id:33,name:"Томша Евгений",f:{receiving:true,forklift_can:true,forklift_job:true,full:true,dark_hair:true,married:true,has_kids:true,has_daughter:true,moldova:true}},
{id:34,name:"Харламов Алексей",f:{placement:true,below_avg:true,full:true,balding:true,divorced:true,has_kids:true,has_daughter:true}},
{id:35,name:"Чайковская Инна",f:{assembly:true,short:true,blonde:true,married:true,has_kids:true,has_son:true,mother_son_here:true,chaykovsky_kin:true,moldova:true}},
{id:36,name:"Чайковский Денис",f:{assembly:true,avg_height:true,thin:true,dark_hair:true,curly:true,unmarried:true,has_kids:false,mother_son_here:true,chaykovsky_kin:true,footballer:true}},
{id:37,name:"Щеголихин Илья",f:{receiving:true,defect:true,avg_height:true,balding:true,unmarried:true,has_kids:false}},
{id:38,name:"Юргелевич Александр",f:{assembly:true,tall:true,thin:true,unmarried:true,has_kids:false,footballer:true}},
{id:39,name:"Тищенко Мария",f:{management:true,chief:true,avg_height:true,blonde:true,married:true,has_kids:true,has_son:true,spouse_here:true,both_mgmt_couple:true,tishchenko_couple:true,sold_car:true,has_car:false}}
], questions: [
{id:"assembly",text:"Этот человек работает на сборке?"},
{id:"management",text:"Это руководство склада?"},
{id:"receiving",text:"Основной участок — приёмка?"},
{id:"placement",text:"Основной участок — размещение?"},
{id:"shipping",text:"Работает на отгрузке?"},
{id:"defect",text:"Работает с браком?"},
{id:"ozon",text:"Работает на участке Ozon или Wildberries?"},
{id:"leroy",text:"Часто собирает заказы Леруа?"},
{id:"married",text:"Женат или замужем?"},
{id:"has_kids",text:"Есть дети?"},
{id:"has_son",text:"Есть сын?"},
{id:"has_daughter",text:"Есть дочь?"},
{id:"spouse_here",text:"Супруг или супруга тоже работает на этом складе?"},
{id:"tall",text:"Высокого роста?"},
{id:"short",text:"Невысокого роста?"},
{id:"athletic",text:"Спортивного телосложения?"},
{id:"thin",text:"Худой?"},
{id:"full",text:"Полного телосложения?"},
{id:"blonde",text:"Светлые волосы?"},
{id:"dark_hair",text:"Тёмные волосы?"},
{id:"bald",text:"Лысый?"},
{id:"moldova",text:"Родом из Молдовы?"},
{id:"has_car",text:"Есть машина?"},
{id:"returned",text:"Увольнялся с этого склада и потом вернулся?"},
{id:"footballer",text:"Играет в футбол?"},
{id:"bets",text:"Делает ставки на спорт?"},
{id:"cap",text:"Постоянно ходит в кепке?"},
{id:"tattoos",text:"Есть татуировки?"},
{id:"limp",text:"Хромает?"},
{id:"andreev_couple",text:"Это Андреев или Андреева?"},
{id:"tishchenko_couple",text:"Это Тищенко Стас или Мария?"},
{id:"sayibov_couple",text:"Это Сайибов или Сайибова?"},
{id:"podaplelov_kin",text:"Это Подаплелов Иван или Павел?"},
{id:"chaykovsky_kin",text:"Это Чайковская или Чайковский?"},
{id:"zhnivin_kin",text:"Это Жнивьин или Савочкин?"},
{id:"nick_volk",text:"Кличка — Волк?"},
{id:"nick_psih",text:"Кличка — Псих?"},
{id:"red_hair",text:"Рыжие волосы?"}
]};
