window.GAME_DATA = { people: [
{id:1,name:"Андреев Сергей",f:{assembly:true,management:true,deputy2:true,avg_height:true,balding:true,cap:true,married:true,has_kids:true,has_daughter:true,spouse_here:true,andreev_couple:true}},
{id:2,name:"Андреева Татьяна",f:{assembly:true,ozon:true,thin:true,blonde:true,married:true,has_kids:true,has_daughter:true,spouse_here:true,spouse_mgmt:true,andreev_couple:true}},
{id:3,name:"Аришев Борис",f:{assembly:true,forklift_can:true,best_picker:true,can_receive:true,can_place:true,full:true,short_cut:true,unmarried:true,has_kids:true,has_daughter:true}},
{id:4,name:"Бабаджанов Афсар",f:{assembly:true,fast_picker:true,married:true,has_kids:true,has_son:true,has_daughter:true,son_and_daughter:true,loud:true}},
{id:5,name:"Воронцов Сергей",f:{assembly:true,former_placement:true,best_picker:true,returned:true,tall:true,graying:true,limp:true,married:true,has_kids:true,has_daughter:true,two_daughters:true,has_car:true,volvo:true,black_volvo:true,nick_volk:true,fight:true}},
{id:6,name:"Галактионов Владимир",f:{placement:true,placement_only:true,married:true,has_kids:true,grandson:true,fussy:true,moonshine:true}},
{id:7,name:"Горковенко Олег",f:{assembly:true,has_car:true,matiz:true}},
{id:8,name:"Дейнеко Паша",f:{assembly:true,avg_height:true,athletic:true,blonde:true,unmarried:true,has_kids:false,has_car:true,nissan:true,detailing:true}},
{id:9,name:"Дудник Сергей",f:{assembly:true,dyed_hair:true,moldova:true}},
{id:10,name:"Жнивьин Алексей",f:{assembly:true,gray_hair:true,graying:true,married:true,has_kids:true,has_son:true,cousin_here:true,zhnivin_kin:true,moonshine:true,scooter:true,nick_psih:true,fight:true}},
{id:12,name:"Карабанова Оля",f:{assembly:true,dark_hair:true,married:true}},
{id:13,name:"Козырь Алексей",f:{assembly:true,can_receive:true,can_place:true,athletic:true,tattoos:true,bets:true,bets_football:true,spartak:true}},
{id:14,name:"Колесников Александр",f:{shipping:true,can_assemble:true,can_place:true,full:true,glasses:true,loud:true}},
{id:15,name:"Краснощекова Ирина",f:{assembly:true,ozon:true,marketplace_lead:true,short_cut:true,married:true}},
{id:16,name:"Кривошеин Паша",f:{assembly:true,leroy:true,leroy_boss:true,avg_height:true,athletic:true,married:true,has_kids:true,has_daughter:true,has_car:true,ford:true}},
{id:17,name:"Ляшенко Саша",f:{placement:true,can_assemble:true,returned:true,sheremetyevo:true,below_avg:true,dark_hair:true,divorced:true,has_kids:true,has_son:true}},
{id:18,name:"Мартынюк Василий",f:{receiving:true,can_assemble:true,can_place:true,short:true,balding:true,unmarried:true,has_kids:false,moldova:true}},
{id:19,name:"Матвеева Елена",f:{assembly:true,ozon_friends:true,leroy_sometimes:true,short:true,blonde:true,married:true,has_kids:true,has_son:true,three_sons:true}},
{id:20,name:"Носова Мария",f:{assembly:true,short:true,full:true,unmarried:true,has_kids:false}},
{id:21,name:"Подаплелов Иван",f:{assembly:true,receiving:true,young:true,dark_hair:true,unmarried:true,has_kids:false,father_son_here:true,podaplelov_kin:true,bets:true,bets_football:true}},
{id:22,name:"Подаплелов Павел",f:{assembly:true,fast_picker:true,married:true,has_kids:true,has_son:true,father_son_here:true,podaplelov_kin:true,has_car:true,lada:true}},
{id:23,name:"Репной Юрий",f:{receiving:true,older:true,graying:true,married:true,has_kids:true,has_son:true,sheremetyevo:true,games:true}},
{id:24,name:"Савочкин Сергей",f:{assembly:true,avg_height:true,dark_hair:true,married:true,has_kids:true,has_son:true,cousin_here:true,zhnivin_kin:true,bets:true,spartak:true}},
{id:25,name:"Сайибов Ойбек",f:{assembly:true,athletic:true,married:true,has_kids:true,spouse_here:true,sayibov_couple:true,has_car:true,priora:true,cherry_priora:true,hoarse:true}},
{id:26,name:"Сайибова Шабнам",f:{assembly:true,dark_hair:true,married:true,has_kids:true,spouse_here:true,sayibov_couple:true}},
{id:27,name:"Седов Александр",f:{assembly:true,short:true,blonde:true,married:true,recently_married:true,rap:true}},
{id:28,name:"Семерикова Алёна",f:{assembly:true,ozon:true,short:true,dark_hair:true,short_cut:true,has_kids:false}},
{id:29,name:"Серов Руслан",f:{placement:true,returned:true,red_hair:true,has_kids:false,has_car:true,mitsubishi:true}},
{id:30,name:"Смирнов Андрей",f:{assembly:true,leroy:true,can_place:true,can_receive:true,above_avg:true,athletic:true,short_cut:true,married:true,has_kids:true,has_son:true,has_car:true,skoda:true,blue_skoda:true}},
{id:31,name:"Степин Виктор",f:{defect:true,defect_receiving:true,full:true,gray_hair:true,older:true,married:true,has_kids:true,has_son:true}},
{id:32,name:"Тищенко Стас",f:{management:true,deputy:true,avg_height:true,bald:true,married:true,has_kids:true,has_son:true,spouse_here:true,spouse_mgmt:true,both_mgmt_couple:true,tishchenko_couple:true}},
{id:33,name:"Томша Евгений",f:{receiving:true,can_assemble:true,can_place:true,forklift_can:true,forklift_job:true,forklift_part:true,full:true,dark_hair:true,married:true,has_kids:true,has_daughter:true,moldova:true}},
{id:34,name:"Харламов Алексей",f:{placement:true,below_avg:true,full:true,balding:true,divorced:true,has_kids:true,has_daughter:true}},
{id:35,name:"Чайковская Инна",f:{assembly:true,short:true,blonde:true,married:true,has_kids:true,has_son:true,mother_son_here:true,chaykovsky_kin:true,moldova:true}},
{id:36,name:"Чайковский Денис",f:{assembly:true,avg_height:true,thin:true,dark_hair:true,curly:true,unmarried:true,has_kids:false,mother_son_here:true,chaykovsky_kin:true,footballer:true}},
{id:37,name:"Щеголихин Илья",f:{receiving:true,defect:true,defect_receiving:true,avg_height:true,balding:true,hides_balding:true,unmarried:true,has_kids:false}},
{id:38,name:"Юргелевич Александр",f:{assembly:true,tall:true,thin:true,unmarried:true,has_kids:false,footballer:true}},
{id:39,name:"Тищенко Мария",f:{management:true,chief:true,avg_height:true,blonde:true,married:true,has_kids:true,has_son:true,spouse_here:true,spouse_mgmt:true,both_mgmt_couple:true,tishchenko_couple:true,sold_car:true,has_car:false}}
], questions: [
{id:"assembly",text:"Ваш персонаж работает на сборке?"},
{id:"receiving",text:"Его основной участок — приёмка?"},
{id:"placement",text:"Его основной участок — размещение?"},
{id:"shipping",text:"Он работает на отгрузке?"},
{id:"defect",text:"Он работает с браком?"},
{id:"ozon",text:"Он работает на участке Ozon/Wildberries?"},
{id:"leroy",text:"Он часто собирает заказы Леруа?"},
{id:"management",text:"Он работает в руководстве склада?"},
{id:"chief",text:"Он начальник склада?"},
{id:"deputy",text:"Он заместитель начальника?"},
{id:"deputy2",text:"Он заместитель заместителя начальника?"},
{id:"forklift_can",text:"Он умеет управлять погрузчиком?"},
{id:"best_picker",text:"Его считают одним из лучших сборщиков?"},
{id:"fast_picker",text:"Он известен быстрой сборкой?"},
{id:"placement_only",text:"Он работает только на размещении?"},
{id:"returned",text:"Он увольнялся с этого склада и вернулся?"},
{id:"sheremetyevo",text:"Он раньше работал в Шереметьево?"},
{id:"tall",text:"Он высокого роста?"},
{id:"short",text:"Он низкого роста?"},
{id:"athletic",text:"У него спортивное телосложение?"},
{id:"thin",text:"Он худой?"},
{id:"full",text:"Он полного телосложения?"},
{id:"blonde",text:"У него светлые волосы?"},
{id:"dark_hair",text:"У него тёмные волосы?"},
{id:"red_hair",text:"У него рыжие волосы?"},
{id:"bald",text:"Он лысый?"},
{id:"balding",text:"Он лысеет?"},
{id:"cap",text:"Он постоянно ходит в кепке?"},
{id:"tattoos",text:"У него есть татуировки?"},
{id:"limp",text:"Он хромает?"},
{id:"married",text:"Он женат или замужем?"},
{id:"unmarried",text:"Он не состоит в браке?"},
{id:"divorced",text:"Он разведён?"},
{id:"has_kids",text:"У него есть дети?"},
{id:"has_son",text:"У него есть сын?"},
{id:"has_daughter",text:"У него есть дочь?"},
{id:"spouse_here",text:"Его супруг или супруга тоже работает на складе?"},
{id:"andreev_couple",text:"Он из семейной пары Андреевых?"},
{id:"tishchenko_couple",text:"Он из семейной пары Тищенко?"},
{id:"sayibov_couple",text:"Он из семейной пары Сайибовых?"},
{id:"father_son_here",text:"На складе работает его отец или сын?"},
{id:"mother_son_here",text:"На складе работает его мать или сын?"},
{id:"cousin_here",text:"На складе работает его двоюродный брат?"},
{id:"has_car",text:"У него есть машина?"},
{id:"matiz",text:"Он ездит на Matiz?"},
{id:"nissan",text:"Он ездит на Nissan?"},
{id:"priora",text:"Он ездит на Priora?"},
{id:"lada",text:"Он ездит на Lada?"},
{id:"volvo",text:"Он ездит на Volvo?"},
{id:"ford",text:"Он ездит на Ford?"},
{id:"skoda",text:"Он ездит на Škoda?"},
{id:"footballer",text:"Он играет в футбол?"},
{id:"spartak",text:"Он болеет за «Спартак»?"},
{id:"bets",text:"Он делает ставки на спорт?"},
{id:"moonshine",text:"Он гонит самогон?"},
{id:"nick_psih",text:"Его кличка Псих?"},
{id:"nick_volk",text:"Его кличка Волк?"},
{id:"moldova",text:"Он родом из Молдовы?"}
]};
